
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    deploy:
      replicas: 2
    environment:
      - CELERY_WORKER_PREFETCH_MULTIPLIER=1
      - CELERY_TASK_RESULT_EXPIRES=3600  # Explicitly set expiration
      - CELERY_RESULT_PERSISTENT=False  # Disable persistent storage

volumes:
  redis_data: